### ISSUE TITLE
More details in case of failure

### ISSUE THREAD

**Issue by 14mr0n** [agido/pageobject#10]
In case of failure, for example if I want to execute a query or click, all I see is something like this

`The code passed to waitFor never returned normally. Attempted 375 times over 10011698572.Last failure message: assertion failed
ScalaTestFailureLocation: org.pageobject.core.TestHelper$ at (TestHelper.scala:57)
org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to waitFor never returned normally. Attempted 375 times over 10011698572.Last failure message: assertion failed
	at org.pageobject.core.TestHelperImpl.timeoutTest(TestHelperImpl.scala:51)
	at org.pageobject.core.TestHelper$.timeoutTest(TestHelper.scala:57)
	at org.pageobject.core.WaitFor$class.tryIt$1(WaitFor.scala:110)
	at org.pageobject.core.WaitFor$class.waitFor(WaitFor.scala:114)
	at org.pageobject.core.WaitFor$$anon$1.waitFor(WaitFor.scala:133)
	at org.pageobject.core.WaitFor$.waitFor(WaitFor.scala:154)`

But it does not tell me what actually went wrong. A message like "Query xyz went wrong" or "click can't be executed" would be nice.

**Comment by drieks** [comment]
Hi,

I changed the `WaitFor` message to show milliseconds, added a `WaitFor` retry debug message showing the cause of retry and added retry logging to Element. I also extended non vnc web drivers to use command tracing. `WaitFor` requires now a message argument of type `String`.

Examples are take from: https://travis-ci.org/agido/pageobject/jobs/228766706

Command tracing:
```
14:54:41.203 DEBUG [#0048] [VNC :1 AnimationTestPage] org.pageobject.core.driver.DefaultTracedRemoteWebDriver - execute getElementLocation(Map(id -> 0 <#animated>)) has taken 24ms

14:55:06.064 DEBUG [#0059] [VNC :1 BrowserErrorPage] org.pageobject.core.driver.DefaultTracedRemoteWebDriver - execute getCurrentUrl() = "http://localhost:35442/span.html" has taken 7ms
14:55:06.102 DEBUG [#0059] [VNC :1 BrowserErrorPage] org.pageobject.core.driver.DefaultTracedRemoteWebDriver - execute findElements("main-frame-error", "id") = 0 Elements: [] has taken 32ms
14:55:06.140 DEBUG [#0059] [VNC :1 BrowserErrorPage] org.pageobject.core.driver.DefaultTracedRemoteWebDriver - execute findElements("link[href="chrome://browser/skin/aboutNetError.css"]", "css selector") = 0 Elements: [] has taken 31ms
```

WaitFor retry showing the cause of the retry
```
14:54:42.262 DEBUG [#0048] [VNC :1 AnimationTestPage] org.pageobject.core.api.UntypedElement - retrying clickAfterAnimation (caused by animation still in progress)

14:58:01.674 DEBUG [#0002] [VNC :2 ] org.pageobject.examples.tour.ExampleSpec - retrying at (caused by assumption failed: Browser is not at expected page GoogleSearchResultPage(Cheese!)!)
```

Element retry information
```
14:57:27.283 DEBUG [#0072] [VNC :1 StaleElementReferencePage] org.pageobject.core.driver.DefaultTracedRemoteWebDriver - execute getElementText("0 <#test1>") exception stale element reference: element is not attached to the page document
  (Session info: chrome=58.0.3029.96)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-51-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-51-generic', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5), userDataDir=/tmp/.org.chromium.Chromium.BEn5Gx}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.96, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: c4cc2985128bc9a0a2626c7da81ce2c5
Command duration or timeout: 357 milliseconds has taken 358ms
14:57:27.284 DEBUG [#0072] [VNC :1 StaleElementReferencePage] org.pageobject.core.api.UntypedElement - retrying Element.text
```

Please let me know if you need more logging!
